package com.myjf.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderItem<M extends BaseOrderItem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setFullName(java.lang.String fullName) {
		set("full_name", fullName);
	}

	public java.lang.String getFullName() {
		return get("full_name");
	}

	public void setIsGift(java.lang.Boolean isGift) {
		set("is_gift", isGift);
	}

	public java.lang.Boolean getIsGift() {
		return get("is_gift");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
	}

	public java.lang.Integer getQuantity() {
		return get("quantity");
	}

	public void setReturnQuantity(java.lang.Integer returnQuantity) {
		set("return_quantity", returnQuantity);
	}

	public java.lang.Integer getReturnQuantity() {
		return get("return_quantity");
	}

	public void setShippedQuantity(java.lang.Integer shippedQuantity) {
		set("shipped_quantity", shippedQuantity);
	}

	public java.lang.Integer getShippedQuantity() {
		return get("shipped_quantity");
	}

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}

	public java.lang.String getSn() {
		return get("sn");
	}

	public void setThumbnail(java.lang.String thumbnail) {
		set("thumbnail", thumbnail);
	}

	public java.lang.String getThumbnail() {
		return get("thumbnail");
	}

	public void setWeight(java.lang.Integer weight) {
		set("weight", weight);
	}

	public java.lang.Integer getWeight() {
		return get("weight");
	}

	public void setOrders(java.lang.Long orders) {
		set("orders", orders);
	}

	public java.lang.Long getOrders() {
		return get("orders");
	}

	public void setProduct(java.lang.Long product) {
		set("product", product);
	}

	public java.lang.Long getProduct() {
		return get("product");
	}

}
