package com.myjf.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleAuthority<M extends BaseRoleAuthority<M>> extends Model<M> implements IBean {

	public void setRole(java.lang.Long role) {
		set("role", role);
	}

	public java.lang.Long getRole() {
		return get("role");
	}

	public void setAuthorities(java.lang.String authorities) {
		set("authorities", authorities);
	}

	public java.lang.String getAuthorities() {
		return get("authorities");
	}

}
