package com.myjf.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMessage<M extends BaseMessage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}

	public java.lang.String getIp() {
		return get("ip");
	}

	public void setIsDraft(java.lang.Boolean isDraft) {
		set("is_draft", isDraft);
	}

	public java.lang.Boolean getIsDraft() {
		return get("is_draft");
	}

	public void setReceiverDelete(java.lang.Boolean receiverDelete) {
		set("receiver_delete", receiverDelete);
	}

	public java.lang.Boolean getReceiverDelete() {
		return get("receiver_delete");
	}

	public void setReceiverRead(java.lang.Boolean receiverRead) {
		set("receiver_read", receiverRead);
	}

	public java.lang.Boolean getReceiverRead() {
		return get("receiver_read");
	}

	public void setSenderDelete(java.lang.Boolean senderDelete) {
		set("sender_delete", senderDelete);
	}

	public java.lang.Boolean getSenderDelete() {
		return get("sender_delete");
	}

	public void setSenderRead(java.lang.Boolean senderRead) {
		set("sender_read", senderRead);
	}

	public java.lang.Boolean getSenderRead() {
		return get("sender_read");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setForMessage(java.lang.Long forMessage) {
		set("for_message", forMessage);
	}

	public java.lang.Long getForMessage() {
		return get("for_message");
	}

	public void setReceiver(java.lang.Long receiver) {
		set("receiver", receiver);
	}

	public java.lang.Long getReceiver() {
		return get("receiver");
	}

	public void setSender(java.lang.Long sender) {
		set("sender", sender);
	}

	public java.lang.Long getSender() {
		return get("sender");
	}

}
