package com.myjf.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShippingMethod<M extends BaseShippingMethod<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setOrders(java.lang.Integer orders) {
		set("orders", orders);
	}

	public java.lang.Integer getOrders() {
		return get("orders");
	}

	public void setContinuePrice(java.math.BigDecimal continuePrice) {
		set("continue_price", continuePrice);
	}

	public java.math.BigDecimal getContinuePrice() {
		return get("continue_price");
	}

	public void setContinueWeight(java.lang.Integer continueWeight) {
		set("continue_weight", continueWeight);
	}

	public java.lang.Integer getContinueWeight() {
		return get("continue_weight");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setFirstPrice(java.math.BigDecimal firstPrice) {
		set("first_price", firstPrice);
	}

	public java.math.BigDecimal getFirstPrice() {
		return get("first_price");
	}

	public void setFirstWeight(java.lang.Integer firstWeight) {
		set("first_weight", firstWeight);
	}

	public java.lang.Integer getFirstWeight() {
		return get("first_weight");
	}

	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}

	public java.lang.String getIcon() {
		return get("icon");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setDefaultDeliveryCorp(java.lang.Long defaultDeliveryCorp) {
		set("default_delivery_corp", defaultDeliveryCorp);
	}

	public java.lang.Long getDefaultDeliveryCorp() {
		return get("default_delivery_corp");
	}

}
