package com.myjf.common.model;

import com.myjf.common.model.base.BaseAd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ad extends BaseAd<Ad> {
	public static final Ad dao = new Ad();
}
