package com.myjf.common.model;

import com.myjf.common.model.base.BaseAdminRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminRole extends BaseAdminRole<AdminRole> {
	public static final AdminRole dao = new AdminRole();
}
