package com.myjf.common.model;

import com.myjf.common.model.base.BaseAdPosition;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdPosition extends BaseAdPosition<AdPosition> {
	public static final AdPosition dao = new AdPosition();
}
