package com.myjf.common.model;

import com.myjf.common.model.base.BaseArticleTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleTag extends BaseArticleTag<ArticleTag> {
	public static final ArticleTag dao = new ArticleTag();
}
