package com.myjf.common.model;

import com.myjf.common.model.base.BaseArticleCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleCategory extends BaseArticleCategory<ArticleCategory> {
	public static final ArticleCategory dao = new ArticleCategory();
}
