package com.myjf.common.model;

import com.myjf.common.model.base.BaseAttributeOption;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AttributeOption extends BaseAttributeOption<AttributeOption> {
	public static final AttributeOption dao = new AttributeOption();
}
