package com.myjf.common.model;

import com.myjf.common.model.base.BaseCartItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CartItem extends BaseCartItem<CartItem> {
	public static final CartItem dao = new CartItem();
}
