package com.myjf.common.model;

import com.myjf.common.model.base.BaseConsultation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Consultation extends BaseConsultation<Consultation> {
	public static final Consultation dao = new Consultation();
}
