package com.myjf.common.model;

import com.myjf.common.model.base.BaseCouponCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CouponCode extends BaseCouponCode<CouponCode> {
	public static final CouponCode dao = new CouponCode();
}
