package com.myjf.common.model;

import com.myjf.common.model.base.BaseCoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Coupon extends BaseCoupon<Coupon> {
	public static final Coupon dao = new Coupon();
}
