package com.myjf.common.model;

import com.myjf.common.model.base.BaseDeliveryCorp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeliveryCorp extends BaseDeliveryCorp<DeliveryCorp> {
	public static final DeliveryCorp dao = new DeliveryCorp();
}
