package com.myjf.common.model;

import com.myjf.common.model.base.BaseDeliveryCenter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeliveryCenter extends BaseDeliveryCenter<DeliveryCenter> {
	public static final DeliveryCenter dao = new DeliveryCenter();
}
