package com.myjf.common.model;

import com.myjf.common.model.base.BaseDeliveryTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeliveryTemplate extends BaseDeliveryTemplate<DeliveryTemplate> {
	public static final DeliveryTemplate dao = new DeliveryTemplate();
}
