package com.myjf.common.model;

import com.myjf.common.model.base.BaseDeposit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Deposit extends BaseDeposit<Deposit> {
	public static final Deposit dao = new Deposit();
}
