package com.myjf.common.model;

import com.myjf.common.model.base.BaseGiftItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GiftItem extends BaseGiftItem<GiftItem> {
	public static final GiftItem dao = new GiftItem();
}
