package com.myjf.common.model;

import com.myjf.common.model.base.BaseMemberFavoriteProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberFavoriteProduct extends BaseMemberFavoriteProduct<MemberFavoriteProduct> {
	public static final MemberFavoriteProduct dao = new MemberFavoriteProduct();
}
