package com.myjf.common.model;

import com.myjf.common.model.base.BaseMemberAttribute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberAttribute extends BaseMemberAttribute<MemberAttribute> {
	public static final MemberAttribute dao = new MemberAttribute();
}
