package com.myjf.common.model;

import com.myjf.common.model.base.BaseMemberAttributeOption;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberAttributeOption extends BaseMemberAttributeOption<MemberAttributeOption> {
	public static final MemberAttributeOption dao = new MemberAttributeOption();
}
