package com.myjf.common.model;

import com.myjf.common.model.base.BaseMemberRank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberRank extends BaseMemberRank<MemberRank> {
	public static final MemberRank dao = new MemberRank();
}
