package com.myjf.common.model;

import com.myjf.common.model.base.BaseNavigation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Navigation extends BaseNavigation<Navigation> {
	public static final Navigation dao = new Navigation();
}
