package com.myjf.common.model;

import com.myjf.common.model.base.BaseOrderCoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderCoupon extends BaseOrderCoupon<OrderCoupon> {
	public static final OrderCoupon dao = new OrderCoupon();
}
