package com.myjf.common.model;

import com.myjf.common.model.base.BaseOrderLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderLog extends BaseOrderLog<OrderLog> {
	public static final OrderLog dao = new OrderLog();
}
