package com.myjf.common.model;

import com.myjf.common.model.base.BaseParameter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Parameter extends BaseParameter<Parameter> {
	public static final Parameter dao = new Parameter();
}
