package com.myjf.common.model;

import com.myjf.common.model.base.BaseParameterGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ParameterGroup extends BaseParameterGroup<ParameterGroup> {
	public static final ParameterGroup dao = new ParameterGroup();
}
