package com.myjf.common.model;

import com.myjf.common.model.base.BasePaymentMethod;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PaymentMethod extends BasePaymentMethod<PaymentMethod> {
	public static final PaymentMethod dao = new PaymentMethod();
}
