package com.myjf.common.model;

import com.myjf.common.model.base.BasePaymentShippingMethod;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PaymentShippingMethod extends BasePaymentShippingMethod<PaymentShippingMethod> {
	public static final PaymentShippingMethod dao = new PaymentShippingMethod();
}
