package com.myjf.common.model;

import com.myjf.common.model.base.BasePayment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Payment extends BasePayment<Payment> {
	public static final Payment dao = new Payment();
}
