package com.myjf.common.model;

import com.myjf.common.model.base.BasePluginConfigAttribute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PluginConfigAttribute extends BasePluginConfigAttribute<PluginConfigAttribute> {
	public static final PluginConfigAttribute dao = new PluginConfigAttribute();
}
