package com.myjf.common.model;

import com.myjf.common.model.base.BasePluginConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PluginConfig extends BasePluginConfig<PluginConfig> {
	public static final PluginConfig dao = new PluginConfig();
}
