package com.myjf.common.model;

import com.myjf.common.model.base.BaseProductNotify;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductNotify extends BaseProductNotify<ProductNotify> {
	public static final ProductNotify dao = new ProductNotify();
}
