package com.myjf.common.model;

import com.myjf.common.model.base.BaseProductSpecificationValue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductSpecificationValue extends BaseProductSpecificationValue<ProductSpecificationValue> {
	public static final ProductSpecificationValue dao = new ProductSpecificationValue();
}
