package com.myjf.common.model;

import com.myjf.common.model.base.BaseProductCategoryBrand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductCategoryBrand extends BaseProductCategoryBrand<ProductCategoryBrand> {
	public static final ProductCategoryBrand dao = new ProductCategoryBrand();
}
