package com.myjf.common.model;

import com.myjf.common.model.base.BaseProductMemberPrice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductMemberPrice extends BaseProductMemberPrice<ProductMemberPrice> {
	public static final ProductMemberPrice dao = new ProductMemberPrice();
}
