package com.myjf.common.model;

import com.myjf.common.model.base.BaseProductProductImage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductProductImage extends BaseProductProductImage<ProductProductImage> {
	public static final ProductProductImage dao = new ProductProductImage();
}
