package com.myjf.common.model;

import com.myjf.common.model.base.BaseProductCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductCategory extends BaseProductCategory<ProductCategory> {
	public static final ProductCategory dao = new ProductCategory();
}
