package com.myjf.common.model;

import com.myjf.common.model.base.BaseProductTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductTag extends BaseProductTag<ProductTag> {
	public static final ProductTag dao = new ProductTag();
}
