package com.myjf.common.model;

import com.myjf.common.model.base.BaseProductParameterValue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductParameterValue extends BaseProductParameterValue<ProductParameterValue> {
	public static final ProductParameterValue dao = new ProductParameterValue();
}
