package com.myjf.common.model;

import com.myjf.common.model.base.BaseProductSpecification;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductSpecification extends BaseProductSpecification<ProductSpecification> {
	public static final ProductSpecification dao = new ProductSpecification();
}
