package com.myjf.common.model;

import com.myjf.common.model.base.BasePromotionMemberRank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PromotionMemberRank extends BasePromotionMemberRank<PromotionMemberRank> {
	public static final PromotionMemberRank dao = new PromotionMemberRank();
}
