package com.myjf.common.model;

import com.myjf.common.model.base.BasePromotionBrand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PromotionBrand extends BasePromotionBrand<PromotionBrand> {
	public static final PromotionBrand dao = new PromotionBrand();
}
