package com.myjf.common.model;

import com.myjf.common.model.base.BasePromotionCoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PromotionCoupon extends BasePromotionCoupon<PromotionCoupon> {
	public static final PromotionCoupon dao = new PromotionCoupon();
}
