package com.myjf.common.model;

import com.myjf.common.model.base.BasePromotionProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PromotionProduct extends BasePromotionProduct<PromotionProduct> {
	public static final PromotionProduct dao = new PromotionProduct();
}
