package com.myjf.common.model;

import com.myjf.common.model.base.BasePromotionProductCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PromotionProductCategory extends BasePromotionProductCategory<PromotionProductCategory> {
	public static final PromotionProductCategory dao = new PromotionProductCategory();
}
