package com.myjf.common.model;

import com.myjf.common.model.base.BaseReceiver;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Receiver extends BaseReceiver<Receiver> {
	public static final Receiver dao = new Receiver();
}
