package com.myjf.common.model;

import com.myjf.common.model.base.BaseRefunds;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Refunds extends BaseRefunds<Refunds> {
	public static final Refunds dao = new Refunds();
}
