package com.myjf.common.model;

import com.myjf.common.model.base.BaseReturns;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Returns extends BaseReturns<Returns> {
	public static final Returns dao = new Returns();
}
