package com.myjf.common.model;

import com.myjf.common.model.base.BaseReturnsItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReturnsItem extends BaseReturnsItem<ReturnsItem> {
	public static final ReturnsItem dao = new ReturnsItem();
}
