package com.myjf.common.model;

import com.myjf.common.model.base.BaseReview;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Review extends BaseReview<Review> {
	public static final Review dao = new Review();
}
