package com.myjf.common.model;

import com.myjf.common.model.base.BaseRoleAuthority;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleAuthority extends BaseRoleAuthority<RoleAuthority> {
	public static final RoleAuthority dao = new RoleAuthority();
}
