package com.myjf.common.model;

import com.myjf.common.model.base.BaseSeo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Seo extends BaseSeo<Seo> {
	public static final Seo dao = new Seo();
}
