package com.myjf.common.model;

import com.myjf.common.model.base.BaseShippingMethod;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShippingMethod extends BaseShippingMethod<ShippingMethod> {
	public static final ShippingMethod dao = new ShippingMethod();
}
