package com.myjf.common.model;

import com.myjf.common.model.base.BaseShipping;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shipping extends BaseShipping<Shipping> {
	public static final Shipping dao = new Shipping();
}
