package com.myjf.common.model;

import com.myjf.common.model.base.BaseShippingItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShippingItem extends BaseShippingItem<ShippingItem> {
	public static final ShippingItem dao = new ShippingItem();
}
