package com.myjf.common.model;

import com.myjf.common.model.base.BaseSn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sn extends BaseSn<Sn> {
	public static final Sn dao = new Sn();
}
