package com.myjf.common.model;

import com.myjf.common.model.base.BaseSpecification;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Specification extends BaseSpecification<Specification> {
	public static final Specification dao = new Specification();
}
