package com.myjf.common.model;

import com.myjf.common.model.base.BaseSpecificationValue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SpecificationValue extends BaseSpecificationValue<SpecificationValue> {
	public static final SpecificationValue dao = new SpecificationValue();
}
