package com.myjf.common.model;

import com.myjf.common.model.base.BaseTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tag extends BaseTag<Tag> {
	public static final Tag dao = new Tag();
}
